spring.application.name=ms-evaluaciones
server.port=8087

eureka.client.service-url.defaultZone=http://ms-eureka:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=jdbc:mysql://mysql:3306/ms_evaluaciones
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true

jwt.secret=miclavesupersecretajwt2026abc123